language : node_js
node_js:
  - '12'
before_install: true

install :
  - npm install

before_script: true

script: true
 - "./node_modules/.bin/retire "
 - "./node_modules/.bin/twly"


after_script: true


deploy: true