language : node_js
node_js :
  - '12'
before_install: true

install :
  - npm install

before_script: true

script:
 - "./node_modules/.bin/retire"
 - "./node_modules/.bin/twly"
 - if [ "$TRAVIS_BRANCH" = "master" ]; then "./node_modules/.bin/twly"; fi

after_script: true


deploy:
  provider: heroku